### ISSUE TITLE
Canopy open/close switch doesn't remain

### ISSUE THREAD

**Issue by ph-jake** [abassign/G91-R1B_HD#11]
Unlocking the canopy and flipping switch (so the panel control, not the keyboard) to 'OPEN' opens the canopy. The switch however reverts to 'CLOSE' position by itself. This makes it impossible to close the canopy again using this switch. 

Using the keyboard controls suggest this is a three way switch with a neutral position in the middle. Then there are two problems:

1. The animation needs to be adapted to show the switch in the neutral position, not in the 'CLOSE' position

1. The click sensitive area around the CLOSE label moves the switch towards the 'OPEN' position, instead of the 'CLOSE' position

**Comment by abassign** [comment]
Thanks for the observation, I just solved the problem, now I update the GIT.

**Comment by ph-jake** [comment]
Not sure if the desired effect is reached here. Let me describe a scenario to reproduce.\
From the start it seems that the canopy switch is a spring loaded three-way switch with a neutral center position. This is where the switch is initially. That is what I'm going to assume is to be correct.\
From the start the canopy is closed, so we start off by opening it. When opening the canopy by clicking the OPEN label the switch briefly transitions to the up position and transitions back to the neutral center. At the same time the canopy starts to open. This is all as expected. But then, after the canopy is fully opened, after a few seconds _the switch transitions to the up position again_.\
From this condition you can close the canopy by clicking the CLOSE label. The switch briefly transitions to the down position and transitions back to the neutral center. At the same time the canopy starts to close. This is all as expected. But then, after the canopy is fully closed, after a few seconds _the switch transitions to the down position again_.\
So there is a strange mix of a neutral center switch and position switch which feels very unnatural, and I assume is unintended.
