### ISSUE TITLE
Transponder codes go beyond what's possible

### ISSUE THREAD

**Issue by ph-jake** [abassign/G91-R1B_HD#13]
The digits of a transponder are _octal_ numbers, each goes from 0..7. Transponder codes go from '0000' to '7777'\
This transponder has decimal numbers, going from 0..9. This allows for impossible transponder codes.

**Comment by abassign** [comment]
Hi, In fact I had not noticed it, as I had not yet configured the transponder and I thank you for your precise observation ... I immediately acted to correct your note and write some JSBSim codeice that should reproduce the transponder more faithfully and connect it, bidirectionally, with the configuration panel located in the system radio menu. I plan to update the GIT tonight, so you can check it too.
One thing I have to ask you, how do I know that the transponder is being interrogated by flight control? Is there any property I need to query?
Thanks :)

**Comment by ph-jake** [comment]
As far as I know there is no implementation of interrogation, the squawk is part of the [Multiplayer protocol messages](http://wiki.flightgear.org/Multiplayer_protocol#Properties_transmitted_over_MP) sent out by the player. It can be found at ID 1500:

1500 | instrumentation/transponder/transmitted-id | INT | TT_SHORTINT | V1_1_PROP_ID
-- | -- | -- | -- | --
