### ISSUE TITLE
Error in file sw_model_no_protection.xml

### ISSUE THREAD

**Issue by scttgs0** [abassign/G91-R1B_HD#9]
Within file  G91-R1B_HD/Models/Parts/Canopy/Lateral_Panels_Left/Pitch_Yaw_Damper/sw_model_no_protection.xml 

line 31 close tag is incorrect. It should be </animation> instead of </effect>

   <animation>
        <type>noshadow</type>
        <object-name>swich_01</object-name>
        <object-name>swich_02</object-name>
        <object-name>swich_03</object-name>
        <object-name>swich_04</object-name>
        <object-name>sw_center</object-name>
        <object-name>sw_north</object-name>
        <object-name>sw_south</object-name>
        <object-name>sw_est</object-name>
        <object-name>sw_west</object-name>
    </effect>

**Comment by abassign** [comment]
Thank, I resolve  this error :)
